var array5 = [
["pow","586","I heard you calling"],
["bro","As It Is When It Was","When last I saw you"],
["bro","As It Is When It Was","Well I always thought"],
["cry","Behind Closed Doors","Underneath a tree"],
["cry","Behind Closed Doors","You will find a key"],
["blu","Blue Monday","When your heart grows cold"],
["bea","Brutal","If you can't decide"],
["bea","Brutal","I'm a shallow man"],
["bea","Brutal","In a hollow land"],
["bea","Brutal","Like a distant dream"],
["bea","Brutal","When it all lived wrong"],
["bea","Brutal","With our love supreme"],
["mov","Chosen Time","All I said to you"],
["mov","Chosen Time","All I did for you"],
["mov","Chosen Time","For a look around"],
["mov","Chosen Time","Who can help me out"],
["get","Close Range","Thirty years or more"],
["get","Close Range","He just wants to score"],
["get","Close Range","You were pretty high"],
["get","Close Range","Looking at the sky"],
["get","Close Range","I remember you"],
["get","Close Range","When you were a kid"],
["get","Close Range","It was pretty strange"],
["get","Close Range","It was on the list"],
["con","Confusion","Searching for more"],
["con","Confusion","Sharing and hoping"],
["con","Confusion","And touched for so long"],
["con","Confusion","You told me you care"],
["con","Confusion","Ask me no questions"],
["con","Confusion","I'll tell you no lies"],
["con","Confusion","The future is mine"],
["con","Confusion","I'll make it this time"],
["con","Confusion","You've taken my place"],
["eve","Cries and Whispers","Below the surface"],
["eve","Cries and Whispers","Inside dimension"],
["eve","Cries and Whispers","All flight departures"],
["eve","Cries and Whispers","Left in these passions"],
["eve","Cries and Whispers","Ship sails out to sea"],
["eve","Cries and Whispers","I just stand and stare"],
["mov","Denial","The answer's not there"],
["mov","Denial","It comes and it goes"],
["mov","Denial","It's not what I need"],
["mov","Denial","Some of it is blurred"],
["tec","Dream Attack","Nothing in this world"],
["bro","Every Second Counts","Every second counts"],
["bro","Every Second Counts","When I am with you"],
["bro","Every Second Counts","I still follow you"],
["rep","Everyone Everywhere","With a single breath"],
["rep","Everyone Everywhere","But we don't falter"],
["eve","Everything's Gone Green","Please show me the way"],
["low","Face Up","I feel so humble"],
["low","Face Up","Cause you know they would"],
["low","Face Up","Cause it's not that way"],
["fin","Fine Time","That's why we could be"],
["fin","Fine Time","You got love technique"],
["wai","Guilt Is A Useless Emotion","Real love can't be bought"],
["wai","Guilt Is A Useless Emotion","Real love can't be sold"],
["wai","Guilt Is A Useless Emotion","Get me on the track"],
["tec","Guilty Partner","I counted on you"],
["tec","Guilty Partner","'Cause I always know"],
["tec","Guilty Partner","You once said to me"],
["tec","Guilty Partner","And all of these words"],
["tec","Guilty Partner","You'll come back to me"],
["her","Here To Stay","He'll get you flying"],
["her","Here To Stay","He'll drive you away"],
["her","Here To Stay","He'll drive you insane"],
["tem","Hurt","Perhaps you hate this"],
["tem","Hurt","I'm quite determined"],
["wai","I Told You So","And I told you so"],
["wai","I Told You So","It's a crazy world"],
["wai","I Told You So","For a mixed-up guy"],
["wai","I Told You So","And an awkward girl"],
["wai","I Told You So","Down the old west side"],
["mov","ICB","It's so far away"],
["mov","ICB","And it's closing in"],
["jet","Jetstream","Right there at the gate"],
["kra","Krafty","Just another night"],
["kra","Krafty","With just one more day"],
["pow","Leave Me Alone","You get these words wrong"],
["rep","Liar","But you sharehold me"],
["rep","Liar","But you betrayed me"],
["low","Love Vigilantes","And some help from God"],
["low","Love Vigilantes","I've got to go home"],
["low","Love Vigilantes","You just can't believe"],
["low","Love Vigilantes","I did not know why"],
["low","Love Vigilantes","But that I was dead"],
["eve","Mesh","All we ever see"],
["eve","Mesh","We made a contract"],
["eve","Mesh","In a field of snow"],
["eve","Mesh","On a frozen floor"],
["wai","Morning Night and Day","Morning night and day"],
["wai","Morning Night and Day","Send me to my fate "],
["wai","Morning Night and Day","It was not my fault "],
["tec","Mr Disco","Oh I can't find you"],
["bro","Paradise","If we left this town"],
["bro","Paradise","If you let me down"],
["her","Player In The League","Who the hell are you?"],
["pro","Procession","I have seen your face"],
["pro","Procession","At night it gets cold"],
["pro","Procession","I can't turn away"],
["pro","Procession","Another picture"],
["reg","Regret","Almost all the time"],
["reg","Regret","I was a short fuse "],
["reg","Regret","Burning all the time"],
["rou","Round and Round","I'll get rid of you"],
["rou","Round and Round","The picture you see"],
["rou","Round and Round","But what can I do?"],
["rou","Round and Round","It ain't so funny"],
["rou","Round and Round","What is it you need"],
["rou","Round and Round","Do you really know?"],
["rou","Round and Round","'cause it doesn't show"],
["rui","Ruined In A Day","Ruined in a day"],
["rui","Ruined In A Day","Your cradle rocking"],
["rui","Ruined In A Day","Don't let me stop you"],
["rui","Ruined In A Day","It could take all day"],
["run","Run","Now that I'm with you"],
["get","Run Wild","To distant places"],
["get","Run Wild","And you're not evil"],
["get","Run Wild","Well you're really cool"],
["get","Run Wild","You could make my day"],
["60m","Sabotage","Change your mind and stay"],
["60m","Sabotage","That we both should play"],
["60m","Sabotage","Maybe I was wrong"],
["60m","Sabotage","Treating you that way"],
["60m","Sabotage","If you're feeling down"],
["60m","Sabotage","I'll turn you around"],
["60m","Sabotage","Sometimes I'm evil"],
["60m","Sabotage","With different people"],
["mov","Senses","I see for their sake"],
["mov","Senses","It shines upon me"],
["mov","Senses","The light of daybreak"],
["mov","Senses","This day we'd all see"],
["mov","Senses","Two ides of recoil"],
["mov","Senses","A failed reminder"],
["mov","Senses","My vague emotions"],
["mov","Senses","This moment's glory"],
["she","Shellshock","It's never enough"],
["she","Shellshock","The deeper you get"],
["she","Shellshock","The sweeter the pain"],
["she","Shellshock","The fire in your soul"],
["get","Slow Jam","It made me feel sick"],
["som","Someone Like You","My heart is burning"],
["som","Someone Like You","The ship has landed"],
["som","Someone Like You","The crew are stranded"],
["som","Someone Like You","Someone like you yeah"],
["low","Sooner Than You Think","There's right and there's wrong"],
["low","Sooner Than You Think","There's good and there's bad"],
["rep","Special","Every drop of wine"],
["rep","Special","You can be my time"],
["rep","Special","Life is but a dream"],
["rep","Special","Covered by the sky"],
["rep","Special","I'm sick of trying"],
["rep","Special","Don't belong with mine"],
["sta","State Of The Nation","State of the nation"],
["wim","Such A Good Thing","Stepping on the grass"],
["wim","Such A Good Thing","Like I always did"],
["wim","Such A Good Thing","Feeling like a kid"],
["wim","Such A Good Thing","Just to watch a game"],
["wim","Such A Good Thing","Sitting on a claim"],
["wim","Such A Good Thing","But I understand"],
["wim","Such A Good Thing","Can't wait for sunrise"],
["wim","Such A Good Thing","High up in the sky"],
["tem","Temptation","Up down turn around"],
["tem","Temptation","Oh you've got green eyes"],
["tem","Temptation","Oh you've got blue eyes"],
["tem","Temptation","Oh you've got grey eyes"],
["tem","Temptation","Oh it's the last time"],
["per","Perfect Kiss","Is the kiss of death"],
["pow","The Village","Same place the wrong time"],
["thi","Thieves Like Us","It's always the same"],
["thi","Thieves Like Us","In the pouring rain"],
["thi","Thieves Like Us","It grows so slowly"],
["thi","Thieves Like Us","It dies so quickly"],
["thi","Thieves Like Us","It belongs to us"],
["thi","Thieves Like Us","And it's so un-cool"],
["low","This Time Of Night","We all feel the same"],
["low","This Time Of Night","Now you know my name"],
["low","This Time Of Night","Now you must decide"],
["low","This Time Of Night","Know the feel of pain"],
["rep","Times Change","I hear it coming"],
["tou","Touched By The Hand Of God","I never knew it"],
["tou","Touched By The Hand Of God","By the hand of God"],
["tou","Touched By The Hand Of God","It belongs to you"],
["tou","Touched By The Hand Of God","But of course I was"],
["tru","True Faith","Again and again"],
["tru","True Faith","I've taken too much"],
["tru","True Faith","Value destiny"],
["tru","True Faith","You took my money"],
["mov","Truth","Oh it's a strange day"],
["wai","Turn","Turn your eyes from me"],
["get","Turn My Way","Thought that I was right"],
["get","Turn My Way","Wait until it's light"],
["pow","Ultraviolence","Who saw those dark eyes"],
["pow","Ultraviolence","All those years gone by"],
["pow","Ultraviolence","Who felt those cold hands"],
["pow","Ultraviolence","All those years ago"],
["pow","Ultraviolence","All those tears ago"],
["tec","Vanishing Point","I've seen all the hate"],
["tec","Vanishing Point","He never gave in"],
["get","Vicious Streak","If you only knew"],
["get","Vicious Streak","My vision is clear"],
["get","Vicious Streak","Whenever you're near"],
["get","Vicious Streak","I keep hanging on"],
["get","Vicious Streak","For someone so young"],
["get","Vicious Streak","You're like solar flair"],
["get","Vicious Streak","In the rising sun"],
["sir","Waiting For The Siren's Call","I won't desert you"],
["sir","Waiting For The Siren's Call","I really hurt you"],
["sir","Waiting For The Siren's Call","I've got it all wrong"],
["bro","Way Of Life","All you say and do"],
["bro","Way Of Life","I know you're lying"],
["bro","Way Of Life","When I look at you"],
["bro","Way Of Life","Seems to fall apart"],
["pow","We All Stand","Life goes on and on"],
["pow","We All Stand","Where all futures go"],
["wai","Who's Joe","And I'll get you home"],
["wai","Who's Joe","Wherever you go"],
["wai","Who's Joe","Whatever you do"],
["wai","Who's Joe","I've got to find you"],
["wai","Who's Joe","And I'll take you there"],
["wai","Who's Joe","It's time to go home"],
["wai","Working Overtime","Who's that over there"],
["wai","Working Overtime","Looks like he don't care"],
["wai","Working Overtime","Almost lost his mind"],
["wai","Working Overtime","He don't need no one"],
["wai","Working Overtime","He's the rising sun"],
["wai","Working Overtime","He won't shed no tears"],
["wai","Working Overtime","Walking down the street"],
["wai","Working Overtime","So much going on"],
["wai","Working Overtime","People everywhere"],
["wai","Working Overtime","See that world out there"],
["wai","Working Overtime","Make it go away"],
["wai","Working Overtime","You can't change his mind"],
["wai","Working Overtime","All those girls out there"],
["wai","Working Overtime","Looking for the one"],
["wai","Working Overtime","Do they really care"],
["wai","Working Overtime","He did all he could"],
["wai","Working Overtime","Tried to get it right"],
["wai","Working Overtime","Somewhere he went wrong"],
["wor","World","Breaking is a crime"],
["wor","World","That's the price of love"],
["wor","World","How long would it last"],
["wim","World In Motion","You know you can win"],
["wim","World In Motion","Don't give up the chase"],
["wim","World In Motion","You never give up"],
["wim","World In Motion","Thats how it should be"],
["wim","World In Motion","Don't give it away"],
["wim","World In Motion","Catch me if you can"],
["wim","World In Motion","Is the master plan"],
["wim","World In Motion","We're playing the song"],
["rep","Young Offender","You are a colour"],
["rep","Young Offender","You are a number"],
["rep","Young Offender","We need a sanction"],
["rep","Young Offender","Stay undercover"],
["rep","Young Offender","Whatever it takes"],
["rep","Young Offender","I will make you mine"],
["rep","Young Offender","Give me the freedom"],
["pow","Your Silent Face","Rise and fall of shame"],
["los","I Told You So","And I told you so"],
["los","I Told You So","It's a crazy world"],
["los","I Told You So","Take her, take the world"],
["los","I Told You So","Down the old west side"],
["los","I'll Stay With You","I won't laugh at you"],
["los","I'll Stay With You","Your world fell apart"],
["los","I'll Stay With You","It cut like a blade"],
["los","I'll Stay With You","And where were your friends"],
["los","I'll Stay With You","You're one of a kind"],
["los","I'll Stay With You","Oh, I'll change your mind"],
["los","Californian Grass","Maybe I can see"],
["los","Californian Grass","Shine a light in there"],
["los","I've Got A Feeling","I can't get no sleep"],
["los","I've Got A Feeling","Things keep going wrong"],
["los","I've Got A Feeling","They don't tell no lies"],
["los","I've Got A Feeling","Driving down the road"],
["los","I've Got A Feeling","I want to be free"],
["los","I've Got A Feeling","I just gotta run"],
["los","I've Got A Feeling","Can't afford to rest"],
["los","I've Got A Feeling","I've got a feeling"],
["los","I've Got A Feeling","Rain is falling down"],
["res","Restless","And how does it feel?"],
["res","Restless","How much do you need?"],
["res","Restless","I want a nice car"],
["res","Restless","I feel so restless"],
["res","Restless","I couldn't care less"],
["res","Restless","Can't be a success"],
["res","Restless","But I kept my nerve"],
["res","Restless","But it's not hopeless"],
["sin","Singularity","Winter came so soon"],
["sin","Singularity","One day at a time"],
["mco","Plastic","Cause you're like plastic"],
["mco","Plastic","You're artificial"],
["mco","Plastic","So superficial"],
["tft","Tutti Frutti","I just want your love"],
["mco","People On The High Line","I'd open the door"],
["mco","People On The High Line","I've been here before"],
["mco","Stray Dog","Why don't you miss me?"],
["mco","Stray Dog","Chose to be with you"],
["mco","Academic","'Cause your heart is cold"],
["mco","Academic","I remember you"],
["mco","Academic","Have you got a face?"],
["mco","Academic","Have you got a soul?"],
["mco","Academic","He ain't got nothing"],
["mco","Nothing But A Fool","And it hurt so much"],
["mco","Nothing But A Fool","Yes, it hurt so much"],
["mco","Nothing But A Fool","She was in my mind"],
["mco","Nothing But A Fool","As I drank my wine"],
["mco","Nothing But A Fool","It's a crying shame"],
["mco","Nothing But A Fool","It caused so much pain"],
["mco","Nothing But A Fool","It turned out that way"],
["mco","Nothing But A Fool","It was me that day"],
["mco","Nothing But A Fool","But what can I do?"],
["mco","Nothing But A Fool","Hold her in your hand"],
["mco","Nothing But A Fool","Feel her in your heart"],
["mco","Unlearn This Hatred","Unlearn this hatred"],
["mco","Unlearn This Hatred","Undo this hatred"],
["mco","Superheated","Now that it's over"],
["mco","Superheated","Did we ever kiss?"],
["mco","Superheated","But it's not your fault"],
["mco","Superheated","Did we ever love?"],
["mco","Superheated","You want your life back"],
["mco","Superheated","Girl I'm not a thief"]
];
