var array7 = [
["tru","1963","I saw hatred in his eyes"],
["tru","1963","He never meant to hurt me"],
["tru","1963","I just want you to be mine"],
["tru","1963","I don't want this world to shine"],
["tru","1963","I don't want this bridge to burn"],
["tru","1963","Oh Johnny do you miss me?"],
["pow","586","On the corner sent by me"],
["pow","586","Straight away you ran from me"],
["pow","586","You will be no friend of mine"],
["pow","586","When I am no longer free"],
["pow","586","When you want me in your heart"],
["pow","586","If you call out in the dark"],
["pow","586","Can you hear me deep inside"],
["pow","586","From these feelings I can't hide"],
["pow","586","Can you hear me calling you"],
["60m","60 Miles An Hour","You can drive down in your car"],
["pow","Age Of Consent","About the birds and the bees"],
["bro","All Day Long","Now I hope you know this song"],
["bro","All Day Long","You scream and shout all day long"],
["tec","All The Way","It takes years to find the nerve"],
["bro","Angel Dust","I fear you will betray me"],
["bro","Angel Dust","What you get is what you need"],
["bro","As It Is When It Was","Whatever you think of me"],
["cry","Behind Closed Doors","I don't know what makes me stay"],
["cry","Behind Closed Doors","Please don't take my drugs away"],
["biz","Bizarre Love Triangle","Every time I think of you"],
["biz","Bizarre Love Triangle","There's no sense in telling me"],
["biz","Bizarre Love Triangle","But that's the way that it goes"],
["biz","Bizarre Love Triangle","And it's what nobody knows"],
["biz","Bizarre Love Triangle","I feel fine and I feel good"],
["biz","Bizarre Love Triangle","I'm not sure what this could mean"],
["biz","Bizarre Love Triangle","I don't think you're what you seem"],
["biz","Bizarre Love Triangle","I do admit to myself"],
["biz","Bizarre Love Triangle","That if I hurt someone else"],
["blu","Blue Monday","I thought I was mistaken"],
["blu","Blue Monday","Tell me now how do I feel"],
["blu","Blue Monday","And I still find it so hard"],
["blu","Blue Monday","To say what I need to say"],
["blu","Blue Monday","Just how I should feel today"],
["bro","Broken Promise","And I never could be true"],
["bro","Broken Promise","And I never could believe"],
["bro","Broken Promise","Then for God's sake I was wrong"],
["bro","Broken Promise","And I'd tear you out of hell"],
["bro","Broken Promise","Because mine lies there as well"],
["bea","Brutal","It's how I want it to be"],
["bea","Brutal","And if you think that you've found"],
["bea","Brutal","And if you can't overcome"],
["cer","Ceremony","Watching her, these things she said"],
["cer","Ceremony","Avenues all lined with trees"],
["cer","Ceremony","Watching love grow forever"],
["cer","Ceremony","Letting me know forever"],
["rep","Chemical","On the payroll company"],
["rep","Chemical","We don't need to hang around"],
["mov","Chosen Time","One day it's now or never"],
["mov","Chosen Time","Sometimes the dreams are better"],
["mov","Chosen Time","Believe that all these changes"],
["mov","Chosen Time","What brought the last reaction"],
["mov","Chosen Time","Sometimes they keep you waiting"],
["get","Close Range","No cold heart could turn away"],
["eve","Cries and Whispers","There's life in another world"],
["eve","Cries and Whispers","And I wasn't even there"],
["cry","Crystal","You can't buy it with money"],
["cry","Crystal","You're not alone anymore"],
["mov","Denial","Like the stain on my windows"],
["mov","Denial","Such a painful companion"],
["mov","Denial","I tried to understand him"],
["mov","Denial","Time worked so well upon us"],
["mov","Doubts Even Here","Which seem to take a lifetime"],
["mov","Doubts Even Here","Collapsing without warning"],
["mov","Doubts Even Here","Beyond all consolation"],
["mov","Doubts Even Here","Thoughts are becoming clearer"],
["mov","Doubts Even Here","All that I need to know now"],
["mov","Doubts Even Here","Why can't I talk to you now?"],
["mov","Doubts Even Here","To know beyond your trust now"],
["mov","Doubts Even Here","Why must you just you leave now?"],
["mov","Doubts Even Here","I need you near to me now"],
["tec","Dream Attack","When I woke up this morning"],
["tec","Dream Attack","I don't belong to noone"],
["tec","Dream Attack","But I want to be with you"],
["tec","Dream Attack","I can't be owned by noone"],
["tec","Dream Attack","What am I supposed to do"],
["tec","Dream Attack","Is it really such a sin"],
["mov","Dreams Never End","My promise could be your fiend"],
["mov","Dreams Never End","A given end to your dreams"],
["mov","Dreams Never End","A simple movement or rhyme"],
["mov","Dreams Never End","Could be the smallest of signs"],
["mov","Dreams Never End","Give in a changing value"],
["mov","Dreams Never End","Hid in a long peaceful night"],
["mov","Dreams Never End","A nervous bride for your eyes"],
["mov","Dreams Never End","A fractured smile that soon dies"],
["mov","Dreams Never End","A savage mine had begun"],
["mov","Dreams Never End","Hello farewell to your soul"],
["bro","Every Second Counts","Though you never let it show"],
["rep","Everyone Everywhere","And if we don't take a chance"],
["rep","Everyone Everywhere","This is no place to shiver"],
["rep","Everyone Everywhere","How could I fail to give her"],
["eve","Everything's Gone Green","Help me somebody help me"],
["low","Face Up","Ever since I've seen your face"],
["low","Face Up","I was young and you were old"],
["low","Face Up","At the start you had a heart"],
["low","Face Up","Can you see your own dark face?"],
["low","Face Up","We were young and we were pure"],
["low","Face Up","You were me and I was you"],
["low","Face Up","I can't hear it anymore"],
["fin","Fine Time","That's why I love you baby"],
["fin","Fine Time","Sophisticated lady"],
["fin","Fine Time","But you've got style you got class"],
["wai","Guilt Is A Useless Emotion","Maybe I'm losing my mind"],
["wai","Guilt Is A Useless Emotion","Searching for another place"],
["wai","Guilt Is A Useless Emotion","Something that you gotta know"],
["wai","Guilt Is A Useless Emotion","You and me just can't go wrong"],
["wai","Guilt Is A Useless Emotion","Standing on top of the world"],
["wai","Guilt Is A Useless Emotion","Thinking of the joy you bring"],
["wai","Guilt Is A Useless Emotion","You could bring the good times back"],
["tec","Guilty Partner","To admit that I was wrong"],
["tec","Guilty Partner","You're not being cool with me"],
["wai","Hey Now What You Doing","Look back at where you came from"],
["wai","Hey Now What You Doing","You had the brightest future"],
["wai","Hey Now What You Doing","What is it that your eyes see"],
["wai","Hey Now What You Doing","Is it love or is it hate"],
["wai","Hey Now What You Doing","Banging on an open gate"],
["wai","Hey Now What You Doing","Turn round don't come no closer"],
["tem","Hurt","I am for you can enjoy"],
["tem","Hurt","It's the time we love to hate"],
["tem","Hurt","I am what you can enjoy"],
["tem","Hurt","It's the time you love to hate"],
["tem","Hurt","I am what you will enjoy"],
["mov","ICB","A tear in a stranger's eye"],
["mov","ICB","When those moments have begun"],
["mov","ICB","Taken from the killing ground"],
["cer","In A Lonely Place","Love that was special for one"],
["cer","In A Lonely Place","Matches an awful delight"],
["cer","In A Lonely Place","Warm like a dog `round your feet"],
["jet","Jetstream","You are my jetstream lover"],
["kra","Krafty","Isn't where you wanna be "],
["pow","Leave Me Alone","We live always underground"],
["pow","Leave Me Alone","And a hundred years ago"],
["pow","Leave Me Alone","Everytime I watch the sky"],
["196","Let's Go","I don't need your sympathy"],
["rep","Liar","You are the king of nothing"],
["rep","Liar","I am the voice of treason"],
["rep","Liar","Because then I'd be faking"],
["rep","Liar","I'm growing tired of waiting"],
["thi","Lonesome Tonight","Could you tell I didn't care?"],
["thi","Lonesome Tonight","When you turned your back on me"],
["thi","Lonesome Tonight","When you reached out in your sleep"],
["thi","Lonesome Tonight","And you knew I wasn't there"],
["thi","Lonesome Tonight","Did you leave my soul alone?"],
["low","Love Vigilantes","With our rifles and grenades"],
["low","Love Vigilantes","And some help from God"],
["low","Love Vigilantes","I've been so alone you see"],
["low","Love Vigilantes","My convictions could not lie"],
["low","Love Vigilantes","For my country I would die"],
["low","Love Vigilantes","And with tears her eyes were sore"],
["low","Love Vigilantes","Then I looked into her hand"],
["low","Love Vigilantes","And I saw the telegram"],
["wai","Morning Night and Day","Two times didn't feel quite right "],
["wai","Morning Night and Day","Other people made that call "],
["tec","Mr Disco","I tried but I can't find you"],
["tec","Mr Disco","Tell me now what do I do"],
["tec","Mr Disco","I can't find my peace of mind"],
["bro","Paradise","There's no place where we can't go"],
["bro","Paradise","There's no place where I have been"],
["bro","Paradise","There's no limit I can show"],
["bro","Paradise","There's no level inbetween"],
["bro","Paradise","There's no place where you can hide"],
["bro","Paradise","There's no place that I can't find"],
["bro","Paradise","There's no end to leave me clean"],
["bro","Paradise","There's no reason I have seen"],
["bro","Paradise","If you find me on my own"],
["bro","Paradise","Shall we leave our world alone"],
["her","Player In The League","I'm getting melancholic"],
["her","Player In The League","But I don't like what you do"],
["her","Player In The League","Why do you care anyway?"],
["her","Player In The League","I can see you everywhere"],
["her","Player In The League","On the ground and in the air"],
["her","Player In The League","You're the one that leaves a trace"],
["her","Player In The League","Like a star in outer space"],
["her","Player In The League","You shine brightly in the sky"],
["her","Player In The League","Underneath the golden eye"],
["her","Player In The League","You've got everything you need"],
["her","Player In The League","You're a player in the league"],
["her","Player In The League","I'm a capable person"],
["pro","Procession","Your heart beats you day and night"],
["reg","Regret","Save it for another day"],
["reg","Regret","You used to be a stranger"],
["reg","Regret","I wouldn't even trust you"],
["reg","Regret","We're dealing in the limits"],
["reg","Regret","I guess that's what they all say "],
["reg","Regret","Just before they fall apart"],
["get","Rock The Shack","I believe in politics"],
["get","Rock The Shack","I believe in everything"],
["get","Rock The Shack","When I hear a baby cry"],
["get","Rock The Shack","When I see an old man die"],
["rou","Round and Round","It makes me act like a child"],
["rou","Round and Round","Don't waste my money baby"],
["rui","Ruined In A Day","There's something wrong you could say"],
["rui","Ruined In A Day","Keeping my life in my hands"],
["rui","Ruined In A Day","I keep my world in my hands"],
["run","Run","So here's what you've got to do"],
["run","Run","Then you break your life in two"],
["run","Run","When you've got what you don't need"],
["run","Run","What the hell is happening"],
["run","Run","I can't think of everything"],
["run","Run","I don't know what day it is"],
["run","Run","But I know that I'm ok"],
["get","Run Wild","But now I'll tell you something"],
["get","Run Wild","But never be a burden"],
["get","Run Wild","Good times around the corner"],
["get","Run Wild","I'm gonna live 'til I die"],
["get","Run Wild","I'm gonna live to get high"],
["60m","Sabotage","What did I do anyway?"],
["60m","Sabotage","We can shake the blues away"],
["60m","Sabotage","The girl is saying again"],
["60m","Sabotage","It's not that easy you say"],
["60m","Sabotage","Sometimes you think I'm ok"],
["60m","Sabotage","No matter how much you cry"],
["60m","Sabotage","That dirt will stay in your eye"],
["60m","Sabotage","It's getting harder to find"],
["60m","Sabotage","But we don't have a deadline"],
["60m","Sabotage","This could be our getaway"],
["60m","Sabotage","We're driving down that highway"],
["she","Shellshock","That's the way that I can win"],
["she","Shellshock","We can't find a peace of mind"],
["she","Shellshock","Until your heart stops beating"],
["she","Shellshock","I've been good and I've been bad"],
["get","Slow Jam","See that bird is floating high"],
["get","Slow Jam","A rich man without his wealth"],
["get","Slow Jam","But I'm not the only one"],
["get","Slow Jam","I got thirsty for a beer"],
["get","Slow Jam","But I like that kind of stuff"],
["get","Slow Jam","I don't want the world to change"],
["get","Slow Jam","I can't get enough of this"],
["get","Slow Jam","When it gets to be alive"],
["get","Slow Jam","I'm a long long way from home"],
["get","Slow Jam","But this photograph of you"],
["get","Slow Jam","Even though it's monochrome"],
["get","Slow Jam","So I got up on my feet"],
["get","Slow Jam","For my clothes were looking beat"],
["get","Slow Jam","In the middle of the night"],
["som","Someone Like You","I guess what I mean to say"],
["som","Someone Like You","The children on holiday"],
["low","Sooner Than You Think","I can see your deep blue eyes"],
["rep","Special","Waiting for the dawn to come"],
["rep","Special","Written in my destiny"],
["rep","Special","Patiently you wait for me"],
["rep","Special","Drowning in the endless sea"],
["spo","Spooky","Maybe we could find a time"],
["spo","Spooky","We'd do everything we could"],
["spo","Spooky","Anytime we wanted to"],
["spo","Spooky","Lets defend the things we say"],
["spo","Spooky","Recreate for me and you"],
["spo","Spooky","A master plan just for two"],
["spo","Spooky","Elevate what's on your mind"],
["sta","State Of The Nation","You can walk or you can run"],
["sta","State Of The Nation","You don't have to be someone"],
["sta","State Of The Nation","I went on a summer cruise"],
["sta","State Of The Nation","Can you see where we can be"],
["sta","State Of The Nation","That's holding our salvation"],
["sta","State Of The Nation","Is causing deprivation"],
["sta","State Of The Nation","It's causing death inflation"],
["sta","State Of The Nation","From my home I travel far"],
["sta","State Of The Nation","I drove in my stolen car"],
["sta","State Of The Nation","I don't find that I have been"],
["sta","State Of The Nation","Where my story had begun?"],
["sta","State Of The Nation","Even now I'm all alone"],
["sta","State Of The Nation","Now we turn across the sea"],
["sub","Subculture","I like walking in the park"],
["sub","Subculture","What do I get out of this"],
["sub","Subculture","In the end you will submit"],
["sub","Subculture","I like talking in my sleep"],
["wim","Such A Good Thing","Just look straight ahead of you"],
["wim","Such A Good Thing","Just do what you wanna do"],
["wim","Such A Good Thing","There's something I could show you"],
["low","Sunrise","Like you never did before"],
["tem","Temptation","Heaven... a gateway of hope"],
["tem","Temptation","Just like a feeling inside"],
["tem","Temptation","Please don't let me hit the ground"],
["per","Perfect Kiss","I stood there beside myself"],
["per","Perfect Kiss","They came by a friend of mine"],
["per","Perfect Kiss","Then I knew it from the start"],
["per","Perfect Kiss","I have always thought about"],
["per","Perfect Kiss","Staying in and going out"],
["per","Perfect Kiss","Playing with my pleasure zone"],
["per","Perfect Kiss","He has always been so strange"],
["per","Perfect Kiss","When you are alone at night"],
["per","Perfect Kiss","If you give it all away"],
["pow","The Village","And the night becomes a bay"],
["pow","The Village","We shall remain forever"],
["pow","The Village","When the rain falls to the sea"],
["pow","The Village","Oh our love is like the earth"],
["pow","The Village","Their love died three years ago"],
["pow","The Village","Spoken words I cannot show"],
["pow","The Village","Our love is like the flowers"],
["pow","The Village","I'm stuck here two years too long"],
["thi","Thieves Like Us","When it dies it dies for good"],
["thi","Thieves Like Us","I've lived my life on the hills"],
["thi","Thieves Like Us","It's called love love love love love"],
["low","This Time Of Night","Without you they'll never know"],
["low","This Time Of Night","Without you my life won't flow"],
["low","This Time Of Night","Without you they'll never show"],
["low","This Time Of Night","Without you the night won't go"],
["low","This Time Of Night","Without you I'm left alone"],
["low","This Time Of Night","Without you I'm on my own"],
["low","This Time Of Night","Without you I lay in pain"],
["low","This Time Of Night","Without you I've gone insane"],
["low","This Time Of Night","Join our world and play our game"],
["low","This Time Of Night","Without you my life's a waste"],
["low","This Time Of Night","Just for you I wrap my face"],
["rep","Times Change","Yellow fever yellow hay"],
["rep","Times Change","Making breaking sacred ground"],
["rep","Times Change","Life will never be the same"],
["rep","Times Change","Ever strange the lives we lead"],
["rep","Times Change","Just when you think you've found it"],
["rep","Times Change","What is wrong? This pain won't peel"],
["tou","Touched By The Hand Of God","Because everything I own"],
["tru","True Faith","Something's got a hold on me"],
["tru","True Faith","I don't care 'cos I'm not there"],
["tru","True Faith","Very small boys talked to me"],
["tru","True Faith","They're afraid of what they see"],
["tru","True Faith","That's the price that we all pay"],
["mov","Truth","I watched my life in a trance"],
["mov","Truth","And the people around me"],
["mov","Truth","Seemed so glad to be here"],
["mov","Truth","Will my time pass so slowly"],
["mov","Truth","Some people look down on me"],
["mov","Truth","I hope they like what they see"],
["wai","Turn","It's a hard way to come home"],
["wai","Turn","In the corner over there"],
["wai","Turn","I want you more than you know"],
["wai","Turn","What do you want me to say"],
["wai","Turn","What we had has gone away"],
["wai","Turn","Show me what I should have done"],
["wai","Turn","What do you want me to do"],
["wai","Turn","Take it all away from you"],
["tec","Vanishing Point","My life ain't no holiday"],
["tec","Vanishing Point","I've seen what a man can do"],
["tec","Vanishing Point","Life is short but love is strong"],
["tec","Vanishing Point","If you try you'll find it too"],
["sir","Waiting For The Siren's Call","What does this ship bring to me"],
["sir","Waiting For The Siren's Call","Far across the restless sea"],
["sir","Waiting For The Siren's Call","Waiting for the sirens' call"],
["sir","Waiting For The Siren's Call","There she plies a lonely trade"],
["sir","Waiting For The Siren's Call","Cutting through the breaking waves"],
["sir","Waiting For The Siren's Call","Drifting slowly from her course"],
["sir","Waiting For The Siren's Call","She is lost forever more"],
["sir","Waiting For The Siren's Call","We all want some kind of love"],
["sir","Waiting For The Siren's Call","But sometimes it's not enough"],
["sir","Waiting For The Siren's Call","To the wall and through the door"],
["sir","Waiting For The Siren's Call","With a stranger on the shore"],
["sir","Waiting For The Siren's Call","Gotta catch the midnight train"],
["sir","Waiting For The Siren's Call","First to Paris then to Spain"],
["sir","Waiting For The Siren's Call","Travel with a document "],
["sir","Waiting For The Siren's Call","All across the continent"],
["sir","Waiting For The Siren's Call","City life is flying by"],
["sir","Waiting For The Siren's Call","Get on board we can't be late"],
["sir","Waiting For The Siren's Call","All the stars and all the worlds"],
["sir","Waiting For The Siren's Call","Filling up this universe"],
["bro","Way Of Life","You told me about yourself"],
["bro","Way Of Life","You told me a pack of lies"],
["bro","Way Of Life","Failure of your moral code"],
["pow","We All Stand","Breath held tight inside of me"],
["bro","Weirdo","I don't care what we have done"],
["bro","Weirdo","You never will believe it"],
["bro","Weirdo","It's a life that's made for me"],
["bro","Weirdo","So I thought this cannot be"],
["bro","Weirdo","I don't care where we have been"],
["bro","Weirdo","I know you and you know me"],
["bro","Weirdo","I know where this world belongs"],
["wai","Working Overtime","Too much working overtime"],
["wai","Working Overtime","Gotta get out every night"],
["wai","Working Overtime","City gates are open wide"],
["wai","Working Overtime","Take that car and push that gear"],
["wai","Working Overtime","Got no time to break down here"],
["wai","Working Overtime","Just a piece of dirty trash"],
["wai","Working Overtime","He don't need nobody else"],
["wai","Working Overtime","Look at him but they don't care"],
["wai","Working Overtime","House music all night long"],
["wai","Working Overtime","Could they just be having fun"],
["wor","World","I turn sideways to the sun"],
["wor","World","Keep my thoughts from everyone"],
["wor","World","It's a jungle I'm a freak"],
["wor","World","Hear me talk but never speak"],
["wor","World","So I'm stepping out of time"],
["wor","World","I've no passion for this hate"],
["wor","World","When this building is on fire"],
["wor","World","In a moment I am gone"],
["wim","World In Motion","Love's got the world in motion"],
["wim","World In Motion","And I know what we can do"],
["wim","World In Motion","And I can't believe its true"],
["wim","World In Motion","But you must get to the line"],
["wim","World In Motion","But do it at the right time"],
["pow","Your Silent Face","A thought that never changes"],
["pow","Your Silent Face","It's never been quite the same"],
["pow","Your Silent Face","It's always been just the same"],
["pow","Your Silent Face","You've caught me at a bad time"],
["los","I'll Stay With You", "Hey, you, what is the matter?"],
["los","I'll Stay With You", "Why did you believe in them?"],
["los","Californian Grass", "Some Californian grass"],
["los","Hellbent", "You're not just anybody"],
["los","I've Got A Feeling", "But the words inside my head"],
["res","Restless","How much, how much do you need?"],
["sin","Singularity","Like summer never happened"],
["sin","Singularity","With roles already scripted"],
["sin","Singularity","On a giant piece of dirt"],
["sin","Singularity","Spinning in the Universe"],
["sin","Singularity","I can hear your cry out there"],
["sin","Singularity","A soldier with no weapon"],
["sin","Singularity","I can feel your presence here"],
["mco","Plastic","Got a feeling in my head"],
["mco","Plastic","Feels like thunder overhead"],
["mco","Plastic","You don't mean nothing, baby"],
["tft","Tutti Frutti","Life is so crazy these days"],
["tft","Tutti Frutti","I don't know how to adjust"],
["tft","Tutti Frutti","Are we the master or slave?"],
["tft","Tutti Frutti","Do we need passion or lust?"],
["tft","Tutti Frutti","Are we just caught in the days?"],
["tft","Tutti Frutti","So many words in a phrase"],
["tft","Tutti Frutti","And I'll never let you go"],
["tft","Tutti Frutti","I had a beautiful dream"],
["tft","Tutti Frutti","Generation's lost in space"],
["mco","People On The High Line","If you love me in the night"],
["mco","People On The High Line","I will come and make it right"],
["mco","People On The High Line","It's all gonna be alright"],
["mco","People On The High Line","I can't get any higher"],
["mco","People On The High Line","There's nothing I desire"],
["mco","Stray Dog","In the darkness of the mire"],
["mco","Stray Dog","So I came in from the cold"],
["mco","Stray Dog","So that I could be with you"],
["mco","Stray Dog","Like the atom and that bomb"],
["mco","Stray Dog","We are forever moving"],
["mco","Nothing But A Fool","But you're nothing but a fool"],
["mco","Nothing But A Fool","When you're left there on your own"],
["mco","Nothing But A Fool","And without a word of lie"],
["mco","Unlearn This Hatred","Two steps forward, one step back"],
["mco","Unlearn This Hatred","Make a sign that I can see"],
["mco","Unlearn This Hatred","Take me to another place"],
["mco","Unlearn This Hatred","Help me win this human race"],
["mco","Unlearn This Hatred","For your healing I can't wait"],
["mco","Unlearn This Hatred","Shoot into my frequency"],
["mco","Unlearn This Hatred","Show me what I have to do"],
["mco","The Game","I want more precious metal"],
["mco","The Game","Taller than a man can reach"],
["mco","Superheated","When you're not here by my side"],
["mco","Superheated","You told me that it's over"]
];
